Removed automatic default group id search on user creation
OpenVPN/terraform-provider-cloudconnexa pull request #35
Opened 2024-07-31 09:36 UTC by michaelfmnk

2024-07-31 13:31 UTC, sahaqaa approved these changes
:+1:

2024-07-31 13:36 UTC, sahaqaa requested changes
UPD: Not working properly when tested against https://github.com/OpenVPN/terraform-provider-cloudconnexa/issues/10

2024-08-01 11:40 UTC, sahaqaa approved these changes
:+1:

2024-08-01 11:41 UTC, arslanbekov approved these changes

2024-08-01 11:43 UTC, merged